# Generated by Django 5.0.6 on 2026-07-05 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atenciones", "0004_profesiograma_tipoexamenrequerido_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("furat", "Plazo FURAT (2 días hábiles)"),
                            ("furel", "Plazo FUREL (2 días hábiles)"),
                            (
                                "adaptacion",
                                "Adaptación de condiciones (20 días hábiles)",
                            ),
                            ("investigacion", "Plazo de investigación"),
                        ],
                        max_length=15,
                    ),
                ),
                ("referencia_modelo", models.CharField(max_length=60)),
                ("referencia_id", models.CharField(max_length=30)),
                ("mensaje", models.CharField(max_length=255)),
                ("vence", models.DateField()),
                ("vencida", models.BooleanField(default=False)),
                ("resuelta", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Alerta de plazo",
                "verbose_name_plural": "Alertas de plazo",
                "ordering": ["resuelta", "vence"],
            },
        ),
        migrations.CreateModel(
            name="InvestigacionAccidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_limite", models.DateField()),
                ("completada", models.BooleanField(default=False)),
                ("conclusiones", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Investigación de accidente",
                "verbose_name_plural": "Investigaciones de accidente",
            },
        ),
        migrations.CreateModel(
            name="ReporteFURAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de envío"),
                            ("enviado", "Enviado a la ARL"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("fecha_limite", models.DateField()),
                ("enviado_at", models.DateTimeField(blank=True, null=True)),
                ("radicado_arl", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "verbose_name": "Reporte FURAT",
                "verbose_name_plural": "Reportes FURAT",
            },
        ),
        migrations.CreateModel(
            name="ReporteFUREL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de envío"),
                            ("enviado", "Enviado a la ARL"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("fecha_limite", models.DateField()),
                ("enviado_at", models.DateTimeField(blank=True, null=True)),
                ("radicado_arl", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "verbose_name": "Reporte FUREL",
                "verbose_name_plural": "Reportes FUREL",
            },
        ),
        migrations.CreateModel(
            name="AccidenteTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("accidente", "Accidente de trabajo (FURAT)"),
                            ("enfermedad", "Enfermedad laboral (FUREL)"),
                        ],
                        default="accidente",
                        max_length=12,
                    ),
                ),
                ("fecha_evento", models.DateField()),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("grave", "Grave"),
                            ("mortal", "Mortal"),
                        ],
                        default="leve",
                        max_length=8,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("arl_nombre", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accidentes",
                        to="atenciones.empresa",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accidentes_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accidentes",
                        to="atenciones.sede",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accidentes",
                        to="atenciones.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accidente / enfermedad laboral",
                "verbose_name_plural": "Accidentes / enfermedades laborales",
                "ordering": ["-fecha_evento"],
            },
        ),
        migrations.AddConstraint(
            model_name="alerta",
            constraint=models.UniqueConstraint(
                fields=("tipo", "referencia_modelo", "referencia_id"),
                name="uniq_alerta_por_referencia",
            ),
        ),
        migrations.AddField(
            model_name="investigacionaccidente",
            name="accidente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investigacion",
                to="accidentes.accidentetrabajo",
            ),
        ),
        migrations.AddField(
            model_name="reportefurat",
            name="accidente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="furat",
                to="accidentes.accidentetrabajo",
            ),
        ),
        migrations.AddField(
            model_name="reportefurel",
            name="accidente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="furel",
                to="accidentes.accidentetrabajo",
            ),
        ),
    ]
