# Generated by Django 5.0.6 on 2026-07-04 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_examen",
                    models.CharField(
                        choices=[
                            ("pre_ingreso", "Pre-ingreso"),
                            ("periodico", "Periódico"),
                            ("egreso", "Egreso"),
                            ("post_incapacidad", "Post-incapacidad"),
                            ("retorno_laboral", "Retorno laboral"),
                            ("seguimiento", "Seguimiento / control"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("espera", "En espera"),
                            ("llamado", "Llamado"),
                            ("atencion", "En atención"),
                            ("paraclinicos", "Paraclínicos"),
                            ("finalizado", "Finalizado"),
                        ],
                        db_index=True,
                        default="registrado",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado_actualizado_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Atención",
                "verbose_name_plural": "Atenciones",
                "ordering": ["estado_actualizado_at"],
            },
        ),
        migrations.CreateModel(
            name="Consultorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Consultorio",
                "verbose_name_plural": "Consultorios",
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Empresa (convenio)",
                "verbose_name_plural": "Empresas (convenios)",
            },
        ),
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("registrado", "Registrado"),
                            ("espera", "En espera"),
                            ("llamado", "Llamado"),
                            ("atencion", "En atención"),
                            ("paraclinicos", "Paraclínicos"),
                            ("finalizado", "Finalizado"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("espera", "En espera"),
                            ("llamado", "Llamado"),
                            ("atencion", "En atención"),
                            ("paraclinicos", "Paraclínicos"),
                            ("finalizado", "Finalizado"),
                        ],
                        max_length=15,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Historial de estado",
                "verbose_name_plural": "Historial de estados",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.CharField(blank=True, max_length=30)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de ciudadanía"),
                            ("CE", "Cédula de extranjería"),
                            ("TI", "Tarjeta de identidad"),
                            ("PA", "Pasaporte"),
                            ("PEP", "Permiso especial de permanencia"),
                            ("PPT", "Permiso por protección temporal"),
                        ],
                        default="CC",
                        max_length=4,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=30)),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("sexo", models.CharField(blank=True, max_length=1)),
                ("cargo", models.CharField(blank=True, max_length=150)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("archivado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
    ]
