# Generated by Django 5.0.6 on 2026-07-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atenciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="atencion",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="atencion",
            name="profesional_asignado",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "medico"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="atencion",
            name="consultorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atenciones",
                to="atenciones.consultorio",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.UniqueConstraint(
                fields=("nit",), name="uniq_empresa_nit"
            ),
        ),
        migrations.AddField(
            model_name="atencion",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones",
                to="atenciones.empresa",
            ),
        ),
        migrations.AddField(
            model_name="historialestado",
            name="atencion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historial_estados",
                to="atenciones.atencion",
            ),
        ),
        migrations.AddField(
            model_name="historialestado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cambios_estado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultorios",
                to="atenciones.sede",
            ),
        ),
        migrations.AddField(
            model_name="atencion",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones",
                to="atenciones.sede",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trabajadores",
                to="atenciones.empresa",
            ),
        ),
        migrations.AddField(
            model_name="atencion",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones",
                to="atenciones.trabajador",
            ),
        ),
        migrations.AddConstraint(
            model_name="trabajador",
            constraint=models.UniqueConstraint(
                fields=("tipo_documento", "numero_documento"),
                name="uniq_trabajador_documento",
            ),
        ),
        migrations.AddIndex(
            model_name="atencion",
            index=models.Index(
                fields=["sede", "estado"], name="atenciones__sede_id_f9c607_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atencion",
            index=models.Index(
                fields=["profesional_asignado", "estado"],
                name="atenciones__profesi_fb3fe6_idx",
            ),
        ),
    ]
