# Generated by Django 5.0.6 on 2026-07-05 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atenciones", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_examen",
                    models.CharField(
                        choices=[
                            ("pre_ingreso", "Pre-ingreso"),
                            ("periodico", "Periódico"),
                            ("egreso", "Egreso"),
                            ("post_incapacidad", "Post-incapacidad"),
                            ("retorno_laboral", "Retorno laboral"),
                            ("seguimiento", "Seguimiento / control"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(db_index=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("confirmada", "Confirmada"),
                            ("cumplida", "Cumplida (admitida)"),
                            ("no_asistio", "No asistió"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="programada",
                        max_length=12,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "atencion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cita",
                        to="atenciones.atencion",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="atenciones.empresa",
                    ),
                ),
                (
                    "profesional_asignado",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "medico"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="atenciones.sede",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="atenciones.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["fecha_hora"],
            },
        ),
    ]
