# Generated by Django 5.0.6 on 2026-07-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atenciones", "0003_cita"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesiograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=150)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profesiogramas",
                        to="atenciones.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesiograma",
                "verbose_name_plural": "Profesiogramas",
            },
        ),
        migrations.CreateModel(
            name="TipoExamenRequerido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_examen",
                    models.CharField(
                        choices=[
                            ("pre_ingreso", "Pre-ingreso"),
                            ("periodico", "Periódico"),
                            ("egreso", "Egreso"),
                            ("post_incapacidad", "Post-incapacidad"),
                            ("retorno_laboral", "Retorno laboral"),
                            ("seguimiento", "Seguimiento / control"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodicidad_meses",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Cada cuántos meses se repite (0 = solo una vez).",
                    ),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                (
                    "profesiograma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examenes",
                        to="atenciones.profesiograma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de examen requerido",
                "verbose_name_plural": "Tipos de examen requeridos",
            },
        ),
        migrations.AddConstraint(
            model_name="profesiograma",
            constraint=models.UniqueConstraint(
                fields=("empresa", "cargo"), name="uniq_profesiograma_empresa_cargo"
            ),
        ),
    ]
