# Generated by Django 5.0.6 on 2026-07-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atenciones", "0004_profesiograma_tipoexamenrequerido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trabajador",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="nombres",
        ),
        migrations.AddField(
            model_name="empresa",
            name="actividad_economica_ciiu",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de actividad económica (CIIU rev. 4 A.C.).",
                max_length=10,
                verbose_name="Código CIIU",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="actividad_economica_desc",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="empresa",
            name="arl_nombre",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="ARL"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="clase_riesgo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Clase I — Riesgo mínimo"),
                    ("II", "Clase II — Riesgo bajo"),
                    ("III", "Clase III — Riesgo medio"),
                    ("IV", "Clase IV — Riesgo alto"),
                    ("V", "Clase V — Riesgo máximo"),
                ],
                default="",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="contacto_sst",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="empresa",
            name="departamento",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="empresa",
            name="digito_verificacion",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
        migrations.AddField(
            model_name="empresa",
            name="municipio",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="empresa",
            name="municipio_dane",
            field=models.CharField(
                blank=True,
                default="",
                max_length=5,
                verbose_name="Código DANE municipio",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="representante_legal",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="empresa",
            name="responsable_sst",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Responsable SST"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="departamento_residencia",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="direccion",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="entidad_responsable_pago",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="EPS / EAPB"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="municipio_dane",
            field=models.CharField(
                blank=True,
                default="",
                max_length=5,
                verbose_name="Código DANE municipio",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="municipio_residencia",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="ocupacion_ciuo",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Ocupación (CIUO)"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="pais_residencia",
            field=models.CharField(default="170", max_length=3),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="pertenencia_etnica",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Indígena"),
                    ("2", "ROM (gitano)"),
                    ("3", "Raizal (San Andrés y Providencia)"),
                    ("4", "Palenquero de San Basilio"),
                    ("5", "Negro(a), mulato(a), afrocolombiano(a)"),
                    ("6", "Ninguna de las anteriores"),
                ],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="primer_apellido",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="primer_nombre",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="segundo_apellido",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="segundo_nombre",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tipo_afiliacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contributivo", "Contributivo"),
                    ("subsidiado", "Subsidiado"),
                    ("especial", "Régimen especial o de excepción"),
                    ("particular", "Particular / No asegurado"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="zona_territorial",
            field=models.CharField(
                blank=True,
                choices=[("U", "Urbana"), ("R", "Rural")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="direccion",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nit",
            field=models.CharField(max_length=20, verbose_name="NIT"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Razón social"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefono",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="cargo",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("I", "Indeterminado / Intersexual"),
                ],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="telefono",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("RC", "Registro civil"),
                    ("TI", "Tarjeta de identidad"),
                    ("CC", "Cédula de ciudadanía"),
                    ("CE", "Cédula de extranjería"),
                    ("PA", "Pasaporte"),
                    ("CN", "Certificado de nacido vivo"),
                    ("AS", "Adulto sin identificación"),
                    ("MS", "Menor sin identificación"),
                    ("PE", "Permiso especial de permanencia"),
                    ("PT", "Permiso por protección temporal"),
                    ("SC", "Salvoconducto"),
                    ("DE", "Documento extranjero"),
                    ("CD", "Carné diplomático"),
                ],
                default="CC",
                max_length=4,
            ),
        ),
    ]
