# Generated by Django 5.0.6 on 2026-07-04 21:26

import apps.usuarios.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atenciones", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombre_completo", models.CharField(max_length=200)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("recepcion", "Recepción / Admisión"),
                            ("medico", "Médico ocupacional"),
                            ("psicologo_sst", "Psicólogo SST"),
                            ("coordinador", "Coordinador / Gerencia IPS"),
                            ("empresa_cliente", "Empresa cliente (portal externo)"),
                            ("admin_sistema", "Administrador de sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa cliente asociada (solo rol empresa_cliente).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios_portal",
                        to="atenciones.empresa",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sede a la que pertenece (recepción, médico, psicólogo).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="atenciones.sede",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
            managers=[
                ("objects", apps.usuarios.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("ver", "Lectura"),
                            ("crear", "Creación"),
                            ("modificar", "Modificación"),
                            ("exportar", "Exportación"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Ej. historia_clinica.HistoriaClinicaOcupacional",
                        max_length=100,
                    ),
                ),
                ("objeto_id", models.CharField(max_length=64)),
                ("campo", models.CharField(blank=True, max_length=100)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Profesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("medico", "Médico ocupacional"),
                            ("psicologo", "Psicólogo SST"),
                        ],
                        max_length=15,
                    ),
                ),
                ("registro_profesional", models.CharField(blank=True, max_length=50)),
                ("especialidad", models.CharField(blank=True, max_length=120)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profesional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesional",
                "verbose_name_plural": "Profesionales",
            },
        ),
        migrations.CreateModel(
            name="LicenciaSST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50)),
                ("entidad_expide", models.CharField(max_length=150)),
                ("fecha_expedicion", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("validada", models.BooleanField(default=False)),
                ("validada_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="usuarios.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licencia SST",
                "verbose_name_plural": "Licencias SST",
            },
        ),
        migrations.AddConstraint(
            model_name="licenciasst",
            constraint=models.UniqueConstraint(
                fields=("profesional", "numero"), name="uniq_licencia_por_profesional"
            ),
        ),
    ]
