# Generated by Django 5.0.6 on 2026-07-04 21:26

import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atenciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentimientoInformado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("general", "Atención general"),
                            ("paraclinicos", "Pruebas complementarias / paraclínicos"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                (
                    "version_documento",
                    models.CharField(
                        help_text="Versión del texto de consentimiento firmado.",
                        max_length=30,
                    ),
                ),
                (
                    "documento_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 del texto firmado.",
                        max_length=64,
                    ),
                ),
                ("firmado_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dispositivo", models.CharField(blank=True, max_length=255)),
                (
                    "firma",
                    models.FileField(
                        blank=True, null=True, upload_to="consentimientos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentimiento informado",
                "verbose_name_plural": "Consentimientos informados",
            },
        ),
        migrations.CreateModel(
            name="DocumentoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("paraclinico", "Resultado de paraclínico"),
                            ("laboratorio", "Laboratorio"),
                            ("imagen", "Imagen diagnóstica"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=15,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("archivo", models.FileField(upload_to="adjuntos/%Y/%m/")),
                ("archivo_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Documento adjunto",
                "verbose_name_plural": "Documentos adjuntos",
            },
        ),
        migrations.CreateModel(
            name="HistoriaClinicaOcupacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo_consulta",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "antecedentes",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "revision_sistemas",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "examen_fisico",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "diagnosticos",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "analisis",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "plan_manejo",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "recomendaciones",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                ("archivada", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Historia clínica ocupacional",
                "verbose_name_plural": "Historias clínicas ocupacionales",
            },
        ),
        migrations.CreateModel(
            name="ConceptoMedicoOcupacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aptitud",
                    models.CharField(
                        choices=[
                            ("apto", "Apto"),
                            (
                                "apto_restricciones",
                                "Apto con restricciones/recomendaciones",
                            ),
                            ("no_apto", "No apto"),
                            ("aplazado", "Aplazado"),
                        ],
                        max_length=25,
                    ),
                ),
                ("restricciones", models.TextField(blank=True)),
                ("recomendaciones_laborales", models.TextField(blank=True)),
                ("firmado", models.BooleanField(default=False)),
                ("fecha_emision", models.DateField(blank=True, null=True)),
                ("vigencia_hasta", models.DateField(blank=True, null=True)),
                ("fecha_recomendacion", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atencion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concepto",
                        to="atenciones.atencion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto médico ocupacional",
                "verbose_name_plural": "Conceptos médicos ocupacionales",
            },
        ),
    ]
