# Generated by Django 5.0.6 on 2026-07-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atenciones", "0002_initial"),
        ("historia_clinica", "0001_initial"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptomedicoocupacional",
            name="licencia_sst",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conceptos",
                to="usuarios.licenciasst",
            ),
        ),
        migrations.AddField(
            model_name="conceptomedicoocupacional",
            name="profesional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conceptos_emitidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentimientoinformado",
            name="atencion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consentimientos",
                to="atenciones.atencion",
            ),
        ),
        migrations.AddField(
            model_name="consentimientoinformado",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consentimientos",
                to="atenciones.trabajador",
            ),
        ),
        migrations.AddField(
            model_name="documentoadjunto",
            name="atencion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjuntos",
                to="atenciones.atencion",
            ),
        ),
        migrations.AddField(
            model_name="documentoadjunto",
            name="subido_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjuntos_subidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historiaclinicaocupacional",
            name="atencion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historia_clinica",
                to="atenciones.atencion",
            ),
        ),
        migrations.AddField(
            model_name="historiaclinicaocupacional",
            name="profesional",
            field=models.ForeignKey(
                limit_choices_to={"rol": "medico"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historias_clinicas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conceptomedicoocupacional",
            name="historia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="concepto",
                to="historia_clinica.historiaclinicaocupacional",
            ),
        ),
    ]
