# Generated by Django 5.0.6 on 2026-07-05 01:58

import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atenciones", "0004_profesiograma_tipoexamenrequerido_and_more"),
        ("historia_clinica", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptomedicoocupacional",
            name="seguimiento_completado",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="InstrumentoPsicosocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("intralaboral", "Cuestionario intralaboral"),
                            ("extralaboral", "Cuestionario extralaboral"),
                            ("estres", "Cuestionario de estrés"),
                            ("ficha", "Ficha de datos sociodemográficos"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "fecha_aplicacion",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("sin_riesgo", "Sin riesgo / despreciable"),
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                            ("muy_alto", "Muy alto"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "contenido",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                ("archivado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aplicado_por",
                    models.ForeignKey(
                        limit_choices_to={"rol": "psicologo_sst"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrumentos_aplicados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "atencion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrumentos_psicosociales",
                        to="atenciones.atencion",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrumentos_psicosociales",
                        to="atenciones.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento psicosocial",
                "verbose_name_plural": "Instrumentos psicosociales",
            },
        ),
    ]
