# Generated by Django 5.0.6 on 2026-07-05 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accidentes", "0001_initial"),
        ("atenciones", "0004_profesiograma_tipoexamenrequerido_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("periodo_desde", models.DateField()),
                ("periodo_hasta", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("emitida", "Emitida"),
                            ("pagada", "Pagada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("emitida_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="atenciones.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura (empresa)",
                "verbose_name_plural": "Facturas (empresas)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FacturaARL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador (RIPS generado)"),
                            ("validada", "Validada (CUV obtenido)"),
                            ("radicada", "Radicada ante la ARL"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                ("rips_json", models.JSONField(default=dict)),
                (
                    "cuv",
                    models.CharField(
                        blank=True,
                        help_text="Código Único de Validación (MUV).",
                        max_length=96,
                    ),
                ),
                (
                    "cucon",
                    models.CharField(
                        blank=True,
                        help_text="Código Único de Contrato (SIIFA).",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accidente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_arl",
                        to="accidentes.accidentetrabajo",
                    ),
                ),
                (
                    "atencion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_arl",
                        to="atenciones.atencion",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_arl_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura ARL (RIPS)",
                "verbose_name_plural": "Facturas ARL (RIPS)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FacturaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "atencion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factura_item",
                        to="atenciones.atencion",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de factura",
                "verbose_name_plural": "Ítems de factura",
            },
        ),
        migrations.CreateModel(
            name="TarifaConvenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_examen", models.CharField(max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarifas",
                        to="atenciones.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de convenio",
                "verbose_name_plural": "Tarifas de convenio",
            },
        ),
        migrations.AddConstraint(
            model_name="tarifaconvenio",
            constraint=models.UniqueConstraint(
                fields=("empresa", "tipo_examen"), name="uniq_tarifa_empresa_examen"
            ),
        ),
    ]
