# Generated by Django 5.0.6 on 2026-07-04 21:26

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20, unique=True)),
                ("codigo_reps", models.CharField(blank=True, max_length=30)),
                ("activo", models.BooleanField(default=True)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "IPS",
                "verbose_name_plural": "IPS",
            },
        ),
        migrations.CreateModel(
            name="Dominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.ips",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
